Modified/added to existing citations
leonoverweel/bibtex-python-package-citations pull request #3
Opened 2019-07-09 20:02 UTC by tpepin96

I modified a few citations to use more up-to-date / authoritative sources.

2019-07-09 20:27 UTC, leonoverweel commented
Thanks, does this overlap a bit with your previous PR? Should we just work/merge on this one?

2019-07-09 20:41 UTC, tpepin96 commented
Yep - it branches off that one. I didn't remove the errant spaces in this yet -- I can remove the spaces from this one and then submit a new PR, would that be good?

2019-07-10 07:32 UTC, leonoverweel commented
Yes, just push to this `fix-citations` branch and it should show up on this PR, I think. I'll close #2 then.

2019-07-10 13:14 UTC, tpepin96 commented
Done! (Thanks for letting me know -- I've not made edits after a PR before.)

2019-07-10 14:26 UTC, leonoverweel requested changes
No problem and thanks! I requested just a few more small changes to make the reference naming consistent with the rest of the repo. I can also merge and make them myself if that's easier, whatever works for you.

2019-07-10 14:26 UTC, leonoverweel commented on README.md
> +@article{jia2014caffe,
Change this to just `caffe`

2019-07-10 14:26 UTC, leonoverweel commented on README.md
> +@InProceedings{manning-EtAl:2014:P14-5,
Change this to just `corenlp`

2019-07-10 14:26 UTC, leonoverweel commented on README.md
> +@misc{chollet2015keras,
Change this to just `keras`

2019-07-10 14:26 UTC, leonoverweel commented on README.md
>  @article{opencv_library,
Change this to just `opencv`

2019-07-10 14:26 UTC, leonoverweel commented on README.md
> +@inproceedings{paszke2017automatic,
Change this to just `pytorch`

2019-07-10 14:26 UTC, leonoverweel commented on README.md
> +@ARTICLE{2016arXiv160502688short,
Change this to `@article{theano,` (lower-case "article")

2019-07-10 14:31 UTC, tpepin96 commented
Yea, you can go ahead and make them! I don't know if it's a point of GitHub etiquette or not, but I have no stake in the matter. I also modified them on my PR if that's easier. (I changed theano as well.)

2019-07-10 14:33 UTC, leonoverweel approved these changes
Perfect, merging.

2019-07-10 14:34 UTC, merged